### ISSUE TITLE
日本語フォントについて

### ISSUE THREAD

**Issue by kazutan** [tokyor/rstudio#2]
先ほどPRした分ですが、mergeしてもらった後の2点に気づきました:

- IPAexフォントじゃなくてIPAフォントを入れている
- DebianならaptでIPA, IPAexフォントを持ってこれる

現時点でもIPA明朝、IPAゴシックが使えるようになっているのですが、どうしましょうか?

**Comment by yutannihilation** [comment]
うーん、レビュー適当ですみません...

@teramonagi ぞうさんをCollaboratorにしちゃえばいい気がしたんですけどどうでしょう？

**Comment by teramonagi** [comment]
是非！（入れます）

**Comment by teramonagi** [comment]
お二人をAdminとして入れておきました〜。
あ、ついでにKazuta氏はtokyorのグループの方にも招待しました。
（こちらだけでよかったのかも。。。）

**Comment by kazutan** [comment]
ありがとうございます!
このissueの件ですが、他のissueと関連してくるので一旦closeしますね
