### ISSUE TITLE
tagの切り分け

### ISSUE THREAD

**Issue by kazutan** [tokyor/rstudio#3]
現時点ではtidyverseをベースとして、多少手を加えたものがlatestになっていると思いますが、せっかくなのでtagでいろんなシチュエーション向けのコンテナを準備するのもありだと思います。

本家rockerは以下のような感じです:

https://hub.docker.com/u/rocker/

こんなに大量でなくても、light版とかtex組み込み版とか、あるいはGIS系やshiny&viz系とかで方向作っておくのもありだと思いますがどうでしょうか?

**Comment by teramonagi** [comment]
ありだと思います。
私の https://github.com/tokyor/rstudio/issues/4 もそれ関連ですね。

STAN入りもそこの１タグとして（Tokyo.R独自に！）整備してしまうのもありかなと。

**Comment by yutannihilation** [comment]
>  私の #4 もそれ関連ですね。

Repository Linksを使うなら、ベースイメージが違うものはタグではなくてイメージを分けた方がいいと思います。

> light版とかtex組み込み版とか、あるいはGIS系やshiny&viz系とかで

これはタグでやるのがいいのかイメージわける方がいいのかどっちでしょうね...。個人的にはイメージわけた方がいい気がします。

**Comment by teramonagi** [comment]
全部イメージわけですねぇ、Pythonなんかもイメージわけてますし（Alpineかそうじゃないかとか）。
タグはRのバージョンとかなんでしょね。

**Comment by kazutan** [comment]
そうですね…DockerfileはこのGitHubリポジトリで管理するとして、用途によってImageを分けたほうがいいかもしれませんね。

**Comment by teramonagi** [comment]
もしかして、それやるなら、各Rockerイメージに全部日本語環境足していくだけの簡単なお仕事でいいんですかね？
https://github.com/rocker-org/rocker/tree/master

**Comment by kazutan** [comment]
https://github.com/tokyor/rstudio/issues/3#issuecomment-353233683
基本それだけでもアリかなと思います。あとは入れといた方がいいパッケージ(githubinstallとか)を必要最小限で組み入れればいいと思います。

**Comment by kazutan** [comment]
運用としては...

- 基本となるimage `tokyor/rstudio` のDockerfileはリポジトリルートに
  - トップのREADME.mdには全体的な説明と各種イメージの紹介
- 別イメージは，イメージ名のディレクトリを準備
  - ディレクトリにはDockerfileとそのイメージ用のREADME.mdを設置
- 別イメージについては，DockerHubで別イメージを準備して，そのディレクトリパスを参照させる
- どんなイメージを立てるかは，その都度issueで議論

こんな感じでいけると思います。

**Comment by teramonagi** [comment]
Rockerだと全部ディレクトリ切ってるんですよねぇ、どうしたもんか・・・・
https://github.com/rocker-org/rocker/tree/master

**Comment by kazutan** [comment]
DockerHubのbuild設定で、buildに使用するDockerfileがあるディレクトリを指定できます。なのでそれでいけるはずです

**Comment by kazutan** [comment]
というわけで、いろいろimageを準備していく方向でいきましょう！
このissueはcloseしますが、また議論が必要だとなったらissueを新たに立てる方向で。
