### ISSUE TITLE
Baseイメージをtidyverseからverseにするのはどうか？

### ISSUE THREAD

**Issue by teramonagi** [tokyor/rstudio#4]
verseはtidyverse + TeX (rJava!!!) なイメージで、Java周りの設定の苦行をしなくていいというメリットがあります。

- https://github.com/rocker-org/rocker-versioned/blob/master/verse/Dockerfile#L11

**Comment by kazutan** [comment]
@teramonagi 試しにrocker/verseから日本語化したのを準備してPR( #6  )出してみました。最終形としてどんな感じにすべきか提案してもらえると助かります。

**Comment by teramonagi** [comment]
PRにコメント開始しました～！

**Comment by kazutan** [comment]
了解です。そしたら一旦こっちはcloseしますね。
